language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:

  include:
  - php: 7.2
  - php: 7.3
  - php: 7.4
  - php: nightly

  fast_finish: true

  allow_failures:
  - php: 7.2
  - php: 7.4
  - php: nightly

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

script:
  - composer test
  - composer lint
